embed Version by make install (#59)
* embed Version by make install

refs #52

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -24,3 +24,16 @@ jobs:
           make setup_ci
           make setup
           make test
+
+      - name: build with version
+        run: |
+          set -x
+          git fetch --unshallow
+          make
+          version=$(./cmd/maprobe/maprobe version 2>&1)
+          if [[ $version == *HEAD* ]]; then
+            echo "failed to embedded version: $version"
+            exit 1
+          else
+            echo "$version"
+          fi
