fix

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -30,8 +30,9 @@ jobs:
           git fetch --unshallow
           make
           version=$(./cmd/maprobe/maprobe version 2>&1)
-          if [[ echo "$version" | grep -q "HEAD" ]]; then
-            echo "failed to embedded version"
+          echo "$version" | grep -q "HEAD"
+          if [[ $? -eq 0 ]]; then
+            echo "failed to embedded version: $version"
             exit 1
           else
             echo $version
